version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: authoy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - authoy-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: authoy-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/portfolio
      - JWT_SECRET=AuthoySuperSecretJWTKey2026!
      - PORT=5000
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - authoy-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: authoy-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - authoy-network

volumes:
  mongo-data:

networks:
  authoy-network:
    driver: bridge
